dataset_params:
  run_num: "BASE_seed_0_2phase_1000epochs"
  root_dir: "/ocean/projects/atm170004p/jakhar/2d_emulator_vision/SSL-for-2D-Turbulence/results/BASE/"
  model_filename: "training_checkpoints/best_ckpt.tar"
  params_filename: "hyperparams.yaml"

short_analysis_params:
# on the fly analysis - plots are saved
  rmse: !!bool False
  acc: !!bool False
  spectra: !!bool False
  spectra_leadtimes: [0, 5, 10, 99]
  analysis_length: 100 # number of training timesteps
  num_ensembles: 2
  test_file_start_idx: 5002
  test_length_climo: 1000
  plot_analysis: !!bool False
  save_short_analysis: !!bool False
  
long_analysis_params:
# For Train: Details would be taken from training config file
  long_analysis_train: !!bool False

# For Truth
  long_analysis_truth: !!bool True
  truth_file_range: [5000, 1504999]

# For emualtor
  long_analysis_emulator: !!bool False
# Data would be saved to perform any long analysis for emulator
  save_data_length: 2 # number of training timesteps emulated and saved
  num_snapshots_per_file: 1 # number of snapshots saved in a single file
  analysis_length: 1500000 # number of trasining timesteps emulated for analysis (
  # For Training data analysis_length is the smaller value in between analysis_length vs training_length

# Analysis
  temporal_mean: !!bool False
  zonal_mean: !!bool False
  spectra: !!bool False
  zonal_U: !!bool True
  zonal_V: !!bool True
  zonal_Omega: !!bool True
  zonal_eof_pc: !!bool False
  eof_ncomp: 3
  PC_autocorr_nlags: 300 # Number of lags (Emulator timesteps) for autocorrelation  # Ensure training/truth data is longer than this (3 times?)
  div: !!bool False
  return_period: !!bool False
  return_period_anomaly: !!bool False # This requires calclation of temporal_mean
  PDF_U: !!bool False # This may need large memory to compute
  PDF_Omega: !!bool False # This may need large memory to compute
  video: !!bool False
  video_length: 300

